checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  environment:
    python: 3.10.4
  nodes:
    tests:
      dependencies:
        before:
          - pip install -r requirements-tests.txt

    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - pylint-run loglan_core

filter:
    excluded_paths:
        - tests/*
tools:
    external_code_coverage: true
