checks:
    python:
        code_rating: true
        duplicate_code: true

tools:
    external_code_coverage:
        timeout: 600

build:
  environment:
    python: 3.12.6
  nodes:
    tests:
      commands:
        before:
          - pip install sqlalchemy
          - pip install setuptools
