checks:
    python:
        code_rating: true
        duplicate_code: true

tools:
    external_code_coverage:
        timeout: 600

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run