"""init db

Revision ID: 07896d9fef5d
Revises: 
Create Date: 2026-10-02 11:24:07.818306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07896d9fef5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('abbreviation', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('annotation', sa.String(length=16), nullable=False),
    sa.Column('suffix', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('keys',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language', name='_word_language_uc')
    )
    op.create_table('settings',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('db_version', sa.Integer(), nullable=False),
    sa.Column('last_word_id', sa.Integer(), nullable=False),
    sa.Column('db_release', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('syllables',
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('type_x', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('parentable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_type'), 'types', ['type'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('origin_x', sa.String(length=64), nullable=True),
    sa.Column('match', sa.String(length=8), nullable=True),
    sa.Column('rank', sa.String(length=8), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('id_old', sa.Integer(), nullable=False),
    sa.Column('TID_old', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('event_start', sa.Integer(), nullable=False),
    sa.Column('event_end', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_end'], ['events.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_start'], ['events.event_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type'], ['types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_event_end'), 'words', ['event_end'], unique=False)
    op.create_index(op.f('ix_words_event_start'), 'words', ['event_start'], unique=False)
    op.create_index(op.f('ix_words_name'), 'words', ['name'], unique=False)
    op.create_index(op.f('ix_words_type'), 'words', ['type'], unique=False)
    op.create_table('connect_authors',
    sa.Column('AID', sa.Integer(), nullable=False),
    sa.Column('WID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AID'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WID'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AID', 'WID')
    )
    op.create_index('index_WID', 'connect_authors', ['WID'], unique=False)
    op.create_table('connect_words',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_index('index_child_id', 'connect_words', ['child_id'], unique=False)
    op.create_table('definitions',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('usage', sa.String(length=64), nullable=True),
    sa.Column('grammar_code', sa.String(length=8), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('case_tags', sa.String(length=16), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_definitions_word_id'), 'definitions', ['word_id'], unique=False)
    op.create_table('connect_keys',
    sa.Column('KID', sa.Integer(), nullable=False),
    sa.Column('DID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DID'], ['definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['KID'], ['keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('KID', 'DID')
    )
    op.create_index('index_DID', 'connect_keys', ['DID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_DID', table_name='connect_keys')
    op.drop_table('connect_keys')
    op.drop_index(op.f('ix_definitions_word_id'), table_name='definitions')
    op.drop_table('definitions')
    op.drop_index('index_child_id', table_name='connect_words')
    op.drop_table('connect_words')
    op.drop_index('index_WID', table_name='connect_authors')
    op.drop_table('connect_authors')
    op.drop_index(op.f('ix_words_type'), table_name='words')
    op.drop_index(op.f('ix_words_name'), table_name='words')
    op.drop_index(op.f('ix_words_event_start'), table_name='words')
    op.drop_index(op.f('ix_words_event_end'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_types_type'), table_name='types')
    op.drop_table('types')
    op.drop_table('syllables')
    op.drop_table('settings')
    op.drop_table('keys')
    op.drop_table('events')
    op.drop_table('authors')
    # ### end Alembic commands ###
