
name: Docs

on: [push]

job-name:
  runs-on: 'ubuntu-latest'
  steps:
    - uses: actions/checkout@v4
    # Builds the documentation package using the standard configuration
    - uses: cascode-labs/build-sphinx-action/action.yml@v0