name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: jpetrucciani/mypy-check@master
        with:
            path: './loglan_core'
            mypy_flags: '--config-file ./pyproject.toml'
