name: Pylint Scores

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: loglan_core
          python-version: ${{ matrix.python-version }}