name: Pytest

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      CC_TEST_REPORTER_ID: 0ab46c7acdcb9951ded95c2cb362eeec513807aa51c459b035509daf84e8f81e

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
      - name: Test with pytest
        run: |
          pytest --cov loglan_core
          bash <(curl -s https://codecov.io/bash)
          ocular --data-file ".coverage" --config-file ".coveragerc"
      - name: Install CodeClimate Test-Reporter
        run: |
          # download test reporter as a static binary
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Run coverage report
        run: |
          ./cc-test-reporter before-build
          ./cc-test-reporter format-coverage -t coverage.py
          ./cc-test-reporter upload-coverage
      - name: Finish build
        run: |
          ./cc-test-reporter after-build --exit-code $?